"""Add bariq_id, username, password to customer

Revision ID: 7e2dde3a3c1a
Revises: bd7f977e9120
Create Date: 2025-12-22 14:22:49.728872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2dde3a3c1a'
down_revision = 'bd7f977e9120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bariq_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_bariq_id'), ['bariq_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_username'))
        batch_op.drop_index(batch_op.f('ix_customers_bariq_id'))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')
        batch_op.drop_column('bariq_id')

    # ### end Alembic commands ###
